from .nodes import (
    NODE_CLASS_MAPPINGS as CORE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CORE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .reference_nodes import (
    NODE_CLASS_MAPPINGS as REFERENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .gdrive_nodes import (
    NODE_CLASS_MAPPINGS as GDRIVE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GDRIVE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .voice_nodes import (
    NODE_CLASS_MAPPINGS as VOICE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VOICE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .scail_runtime_nodes import (
    NODE_CLASS_MAPPINGS as SCAIL_RUNTIME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCAIL_RUNTIME_NODE_DISPLAY_NAME_MAPPINGS,
)
from .output_nodes import (
    NODE_CLASS_MAPPINGS as OUTPUT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OUTPUT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .stream_nodes import (
    NODE_CLASS_MAPPINGS as STREAM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STREAM_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **CORE_NODE_CLASS_MAPPINGS,
    **REFERENCE_NODE_CLASS_MAPPINGS,
    **GDRIVE_NODE_CLASS_MAPPINGS,
    **VOICE_NODE_CLASS_MAPPINGS,
    **SCAIL_RUNTIME_NODE_CLASS_MAPPINGS,
    **OUTPUT_NODE_CLASS_MAPPINGS,
    **STREAM_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CORE_NODE_DISPLAY_NAME_MAPPINGS,
    **REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
    **GDRIVE_NODE_DISPLAY_NAME_MAPPINGS,
    **VOICE_NODE_DISPLAY_NAME_MAPPINGS,
    **SCAIL_RUNTIME_NODE_DISPLAY_NAME_MAPPINGS,
    **OUTPUT_NODE_DISPLAY_NAME_MAPPINGS,
    **STREAM_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
